language: python
cache: pip
python:
  - "3.7"
  - "3.8"
before_install:
  - pip install poetry
install:
  - poetry install
  - gem install mdl
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - mdl README.md
  - poetry run flake8 webapp
  - poetry run pytest --cov=./ tests/ --cov-report=xml
  - opensource_watchman sanchos2 --repo_name=nautilus
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - codecov