"""add organization column to receipt

Revision ID: 3b5bbd75c8df
Revises: cf53693abea5
Create Date: 2020-04-17 07:43:02.273193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5bbd75c8df'
down_revision = 'cf53693abea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('organization', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt', 'organization')
    # ### end Alembic commands ###
