"""add organization column to purchase and remove it from receipt

Revision ID: 6b4d8fda99d1
Revises: 3b5bbd75c8df
Create Date: 2020-04-17 08:29:31.566972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4d8fda99d1'
down_revision = '3b5bbd75c8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('organization', sa.String(), nullable=True))
    op.drop_column('receipt', 'organization')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('organization', sa.VARCHAR(), nullable=True))
    op.drop_column('purchase', 'organization')
    # ### end Alembic commands ###
