"""add telephone to user

Revision ID: 78d2adacc282
Revises: a30f4e709c72
Create Date: 2020-04-02 14:27:59.624397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d2adacc282'
down_revision = 'a30f4e709c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telephone', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telephone')
    # ### end Alembic commands ###
