"""add ltree to purchase

Revision ID: 8e9e5bcada6e
Revises: 38a02fafec6b
Create Date: 2020-04-24 19:34:59.292777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9e5bcada6e'
down_revision = '38a02fafec6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('tree', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchase_tree'), 'purchase', ['tree'], unique=False)
    op.create_foreign_key(None, 'purchase', 'category_tree', ['tree'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_tree'), table_name='purchase')
    op.drop_column('purchase', 'tree')
    # ### end Alembic commands ###
