"""empty message

Revision ID: e4c839e36136
Revises: 
Create Date: 2020-04-20 16:49:58.490551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c839e36136'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('fns_login', sa.String(length=12), nullable=True),
    sa.Column('fns_password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fn_number', sa.String(), nullable=True),
    sa.Column('fd_number', sa.String(), nullable=True),
    sa.Column('fpd_number', sa.String(), nullable=True),
    sa.Column('receipt_type', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sum', sa.Float(), nullable=True),
    sa.Column('loaded', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_user_id'), 'purchase', ['user_id'], unique=False)
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategory_category_id'), 'subcategory', ['category_id'], unique=False)
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('sum', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('subcategory', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory'], ['subcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_category'), 'receipt', ['category'], unique=False)
    op.create_index(op.f('ix_receipt_purchase_id'), 'receipt', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_receipt_subcategory'), 'receipt', ['subcategory'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_subcategory'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_purchase_id'), table_name='receipt')
    op.drop_index(op.f('ix_receipt_category'), table_name='receipt')
    op.drop_table('receipt')
    op.drop_index(op.f('ix_subcategory_category_id'), table_name='subcategory')
    op.drop_table('subcategory')
    op.drop_index(op.f('ix_purchase_user_id'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
