"""add valid column to purchase

Revision ID: f131ffc2c93a
Revises: 2d3389abdc18
Create Date: 2020-04-07 15:36:30.555059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f131ffc2c93a'
down_revision = '2d3389abdc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('valid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'valid')
    # ### end Alembic commands ###
